In [2]:
import pandas as pd

data = pd.read_csv("../data/raw/owid-energy-data.csv")

In [3]:
data.shape

(23377, 130)

In [4]:
data.columns.tolist()

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'biofuel_cons_change_pct',
 'biofuel_cons_change_twh',
 'biofuel_cons_per_capita',
 'biofuel_consumption',
 'biofuel_elec_per_capita',
 'biofuel_electricity',
 'biofuel_share_elec',
 'biofuel_share_energy',
 'carbon_intensity_elec',
 'coal_cons_change_pct',
 'coal_cons_change_twh',
 'coal_cons_per_capita',
 'coal_consumption',
 'coal_elec_per_capita',
 'coal_electricity',
 'coal_prod_change_pct',
 'coal_prod_change_twh',
 'coal_prod_per_capita',
 'coal_production',
 'coal_share_elec',
 'coal_share_energy',
 'electricity_demand',
 'electricity_demand_per_capita',
 'electricity_generation',
 'electricity_share_energy',
 'energy_cons_change_pct',
 'energy_cons_change_twh',
 'energy_per_capita',
 'energy_per_gdp',
 'fossil_cons_change_pct',
 'fossil_cons_change_twh',
 'fossil_elec_per_capita',
 'fossil_electricity',
 'fossil_energy_per_capita',
 'fossil_fuel_consumption',
 'fossil_share_elec',
 'fossil_share_energy',
 'gas_cons_change_pct',
 'gas_cons_change_twh',
 'gas_consumption',
 'gas_elec_per_capita',
 'gas_electricity',
 'gas_energy_per_capita',
 'gas_prod_change_pct',
 'gas_prod_change_twh',
 'gas_prod_per_capita',
 'gas_production',
 'gas_share_elec',
 'gas_share_energy',
 'greenhouse_gas_emissions',
 'hydro_cons_change_pct',
 'hydro_cons_change_twh',
 'hydro_consumption',
 'hydro_elec_per_capita',
 'hydro_electricity',
 'hydro_energy_per_capita',
 'hydro_share_elec',
 'hydro_share_energy',
 'low_carbon_cons_change_pct',
 'low_carbon_cons_change_twh',
 'low_carbon_consumption',
 'low_carbon_elec_per_capita',
 'low_carbon_electricity',
 'low_carbon_energy_per_capita',
 'low_carbon_share_elec',
 'low_carbon_share_energy',
 'net_elec_imports',
 'net_elec_imports_share_demand',
 'nuclear_cons_change_pct',
 'nuclear_cons_change_twh',
 'nuclear_consumption',
 'nuclear_elec_per_capita',
 'nuclear_electricity',
 'nuclear_energy_per_capita',
 'nuclear_share_elec',
 'nuclear_share_energy',
 'oil_cons_change_pct',
 'oil_cons_change_twh',
 'oil_consumption',
 'oil_elec_per_capita',
 'oil_electricity',
 'oil_energy_per_capita',
 'oil_prod_change_pct',
 'oil_prod_change_twh',
 'oil_prod_per_capita',
 'oil_production',
 'oil_share_elec',
 'oil_share_energy',
 'other_renewable_consumption',
 'other_renewable_electricity',
 'other_renewable_exc_biofuel_electricity',
 'other_renewables_cons_change_pct',
 'other_renewables_cons_change_twh',
 'other_renewables_elec_per_capita',
 'other_renewables_elec_per_capita_exc_biofuel',
 'other_renewables_energy_per_capita',
 'other_renewables_share_elec',
 'other_renewables_share_elec_exc_biofuel',
 'other_renewables_share_energy',
 'per_capita_electricity',
 'primary_energy_consumption',
 'renewables_cons_change_pct',
 'renewables_cons_change_twh',
 'renewables_consumption',
 'renewables_elec_per_capita',
 'renewables_electricity',
 'renewables_energy_per_capita',
 'renewables_share_elec',
 'renewables_share_energy',
 'solar_cons_change_pct',
 'solar_cons_change_twh',
 'solar_consumption',
 'solar_elec_per_capita',
 'solar_electricity',
 'solar_energy_per_capita',
 'solar_share_elec',
 'solar_share_energy',
 'wind_cons_change_pct',
 'wind_cons_change_twh',
 'wind_consumption',
 'wind_elec_per_capita',
 'wind_electricity',
 'wind_energy_per_capita',
 'wind_share_elec',
 'wind_share_energy']

In [5]:
for col in data.columns:
    if "renew" in col.lower():
        print(col)

other_renewable_consumption
other_renewable_electricity
other_renewable_exc_biofuel_electricity
other_renewables_cons_change_pct
other_renewables_cons_change_twh
other_renewables_elec_per_capita
other_renewables_elec_per_capita_exc_biofuel
other_renewables_energy_per_capita
other_renewables_share_elec
other_renewables_share_elec_exc_biofuel
other_renewables_share_energy
renewables_cons_change_pct
renewables_cons_change_twh
renewables_consumption
renewables_elec_per_capita
renewables_electricity
renewables_energy_per_capita
renewables_share_elec
renewables_share_energy

In [7]:
for col in data.columns:
    if "co2" in col.lower():
        print(col)

In [8]:
for col in data.columns:
    if "emission" in col.lower():
        print(col)

greenhouse_gas_emissions

In [9]:
data.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [10]:
data[['country', 'year', 'renewables_share_energy']].head(20)

          country  year  renewables_share_energy
0   ASEAN (Ember)  2000                      NaN
1   ASEAN (Ember)  2001                      NaN
2   ASEAN (Ember)  2002                      NaN
3   ASEAN (Ember)  2003                      NaN
4   ASEAN (Ember)  2004                      NaN
5   ASEAN (Ember)  2005                      NaN
6   ASEAN (Ember)  2006                      NaN
7   ASEAN (Ember)  2007                      NaN
8   ASEAN (Ember)  2008                      NaN
9   ASEAN (Ember)  2009                      NaN
10  ASEAN (Ember)  2010                      NaN
11  ASEAN (Ember)  2011                      NaN
12  ASEAN (Ember)  2012                      NaN
13  ASEAN (Ember)  2013                      NaN
14  ASEAN (Ember)  2014                      NaN
15  ASEAN (Ember)  2015                      NaN
16  ASEAN (Ember)  2016                      NaN
17  ASEAN (Ember)  2017                      NaN
18  ASEAN (Ember)  2018                      NaN
19  ASEAN (Ember)  2019                      NaN

In [11]:
data['country'].unique()[:20]

<StringArray>
[         'ASEAN (Ember)',            'Afghanistan',                 'Africa',
            'Africa (EI)',           'Africa (EIA)',         'Africa (Ember)',
         'Africa (Shift)',                'Albania',                'Algeria',
         'American Samoa',                 'Angola',             'Antarctica',
    'Antigua and Barbuda',              'Argentina',                'Armenia',
                  'Aruba',                   'Asia',           'Asia (Ember)',
      'Asia Pacific (EI)', 'Asia and Oceania (EIA)']
Length: 20, dtype: str

In [13]:
data['country'].unique()[:50]

<StringArray>
[                  'ASEAN (Ember)',                     'Afghanistan',
                          'Africa',                     'Africa (EI)',
                    'Africa (EIA)',                  'Africa (Ember)',
                  'Africa (Shift)',                         'Albania',
                         'Algeria',                  'American Samoa',
                          'Angola',                      'Antarctica',
             'Antigua and Barbuda',                       'Argentina',
                         'Armenia',                           'Aruba',
                            'Asia',                    'Asia (Ember)',
               'Asia Pacific (EI)',          'Asia and Oceania (EIA)',
        'Asia and Oceania (Shift)',                       'Australia',
 'Australia and New Zealand (EIA)',                         'Austria',
                      'Azerbaijan',                         'Bahamas',
                         'Bahrain',                      'Bangladesh',
                        'Barbados',                         'Belarus',
                         'Belgium',                          'Belize',
                           'Benin',                         'Bermuda',
                          'Bhutan',                         'Bolivia',
          'Bosnia and Herzegovina',                        'Botswana',
                          'Brazil',          'British Virgin Islands',
                          'Brunei',                        'Bulgaria',
                    'Burkina Faso',                         'Burundi',
                        'CIS (EI)',                        'Cambodia',
                        'Cameroon',                          'Canada',
                      'Cape Verde',                  'Cayman Islands']
Length: 50, dtype: str

In [14]:
data[data['renewables_share_energy'].notna()][['country','year','renewables_share_energy']].head(20)

    country  year  renewables_share_energy
216  Africa  1965                 5.419266
217  Africa  1966                 5.772398
218  Africa  1967                 5.963763
219  Africa  1968                 6.605470
220  Africa  1969                 7.505726
221  Africa  1970                 8.649540
222  Africa  1971                 7.689221
223  Africa  1972                 8.276323
224  Africa  1973                 8.068716
225  Africa  1974                 8.736290
226  Africa  1975                 8.713099
227  Africa  1976                 8.906370
228  Africa  1977                 9.280894
229  Africa  1978                 9.005293
230  Africa  1979                 8.839782
231  Africa  1980                 8.006187
232  Africa  1981                 7.404695
233  Africa  1982                 6.944731
234  Africa  1983                 6.091397
235  Africa  1984                 5.818251

In [15]:
data[data['country'] == 'Germany'][['country','year','renewables_share_energy']].tail(10)

      country  year  renewables_share_energy
8273  Germany  2016                14.101188
8274  Germany  2017                15.387794
8275  Germany  2018                16.262758
8276  Germany  2019                17.811209
8277  Germany  2020                20.017168
8278  Germany  2021                18.082499
8279  Germany  2022                20.329155
8280  Germany  2023                23.602962
8281  Germany  2024                23.968008
8282  Germany  2025                      NaN

In [16]:
data[data['country'] == 'India'][['country','year','renewables_share_energy']].tail(10)

     country  year  renewables_share_energy
9690   India  2016                 6.369765
9691   India  2017                 6.792767
9692   India  2018                 7.307381
9693   India  2019                 8.108068
9694   India  2020                 8.892713
9695   India  2021                 8.656782
9696   India  2022                 9.421208
9697   India  2023                 8.860951
9698   India  2024                 9.146443
9699   India  2025                      NaN

In [17]:
for col in data.columns:
    if "carbon" in col.lower():
        print(col)

carbon_intensity_elec
low_carbon_cons_change_pct
low_carbon_cons_change_twh
low_carbon_consumption
low_carbon_elec_per_capita
low_carbon_electricity
low_carbon_energy_per_capita
low_carbon_share_elec
low_carbon_share_energy

In [18]:
for col in data.columns:
    if "greenhouse" in col.lower():
        print(col)

greenhouse_gas_emissions

In [19]:
for col in data.columns:
    if "emission" in col.lower():
        print(col)

greenhouse_gas_emissions

In [20]:
data[data['country'] == 'Germany'][['country','year','greenhouse_gas_emissions']].tail(10)

      country  year  greenhouse_gas_emissions
8273  Germany  2016                319.670013
8274  Germany  2017                302.709991
8275  Germany  2018                287.399994
8276  Germany  2019                235.539993
8277  Germany  2020                201.539993
8278  Germany  2021                228.429993
8279  Germany  2022                237.940002
8280  Germany  2023                183.899994
8281  Germany  2024                166.839996
8282  Germany  2025                164.979996

In [21]:
data[data['country'] == 'India'][['country','year','greenhouse_gas_emissions']].tail(10)

     country  year  greenhouse_gas_emissions
9690   India  2016               1048.810059
9691   India  2017               1086.680054
9692   India  2018               1159.439941
9693   India  2019               1156.959961
9694   India  2020               1108.560059
9695   India  2021               1200.849976
9696   India  2022               1273.609985
9697   India  2023               1368.410034
9698   India  2024               1436.569946
9699   India  2025               1394.949951

In [22]:
data['greenhouse_gas_emissions'].describe()

count     6028.000000
mean       339.994720
std       1384.212978
min          0.000000
25%          0.300000
50%          3.330000
75%         40.684999
max      14570.480469
Name: greenhouse_gas_emissions, dtype: float64

In [24]:
countries = [
    "Germany",
    "India",
    "China",
    "United States",
    "France",
    "Spain",
    "Italy"
]

In [25]:
project_data = data[
    data['country'].isin(countries)
]

In [26]:
project_data = project_data[
    [
        'country',
        'year',
        'renewables_share_energy',
        'greenhouse_gas_emissions'
    ]
]

In [27]:
project_data.head()

     country  year  renewables_share_energy  greenhouse_gas_emissions
4482   China  1900                      NaN                       NaN
4483   China  1901                      NaN                       NaN
4484   China  1902                      NaN                       NaN
4485   China  1903                      NaN                       NaN
4486   China  1904                      NaN                       NaN

In [28]:
project_data.shape

(882, 4)

In [29]:
project_data = project_data.dropna()

In [30]:
project_data.shape

(175, 4)

In [31]:
project_data.head()

     country  year  renewables_share_energy  greenhouse_gas_emissions
4582   China  2000                 5.335688               1062.119995
4583   China  2001                 6.251407               1129.670044
4584   China  2002                 5.921867               1279.040039
4585   China  2003                 5.001339               1511.109985
4586   China  2004                 5.289435               1715.280029

In [32]:
co2_data = pd.read_csv("../data/raw/owid-co2-data.csv")

In [33]:
co2_data.shape

(50411, 79)

In [34]:
co2_data.columns.tolist()

['country',
 'year',
 'iso_code',
 'population',
 'gdp',
 'cement_co2',
 'cement_co2_per_capita',
 'co2',
 'co2_growth_abs',
 'co2_growth_prct',
 'co2_including_luc',
 'co2_including_luc_growth_abs',
 'co2_including_luc_growth_prct',
 'co2_including_luc_per_capita',
 'co2_including_luc_per_gdp',
 'co2_including_luc_per_unit_energy',
 'co2_per_capita',
 'co2_per_gdp',
 'co2_per_unit_energy',
 'coal_co2',
 'coal_co2_per_capita',
 'consumption_co2',
 'consumption_co2_per_capita',
 'consumption_co2_per_gdp',
 'cumulative_cement_co2',
 'cumulative_co2',
 'cumulative_co2_including_luc',
 'cumulative_coal_co2',
 'cumulative_flaring_co2',
 'cumulative_gas_co2',
 'cumulative_luc_co2',
 'cumulative_oil_co2',
 'cumulative_other_co2',
 'energy_per_capita',
 'energy_per_gdp',
 'flaring_co2',
 'flaring_co2_per_capita',
 'gas_co2',
 'gas_co2_per_capita',
 'ghg_excluding_lucf_per_capita',
 'ghg_per_capita',
 'land_use_change_co2',
 'land_use_change_co2_per_capita',
 'methane',
 'methane_per_capita',
 'nitrous_oxide',
 'nitrous_oxide_per_capita',
 'oil_co2',
 'oil_co2_per_capita',
 'other_co2_per_capita',
 'other_industry_co2',
 'primary_energy_consumption',
 'share_global_cement_co2',
 'share_global_co2',
 'share_global_co2_including_luc',
 'share_global_coal_co2',
 'share_global_cumulative_cement_co2',
 'share_global_cumulative_co2',
 'share_global_cumulative_co2_including_luc',
 'share_global_cumulative_coal_co2',
 'share_global_cumulative_flaring_co2',
 'share_global_cumulative_gas_co2',
 'share_global_cumulative_luc_co2',
 'share_global_cumulative_oil_co2',
 'share_global_cumulative_other_co2',
 'share_global_flaring_co2',
 'share_global_gas_co2',
 'share_global_luc_co2',
 'share_global_oil_co2',
 'share_global_other_co2',
 'share_of_temperature_change_from_ghg',
 'temperature_change_from_ch4',
 'temperature_change_from_co2',
 'temperature_change_from_ghg',
 'temperature_change_from_n2o',
 'total_ghg',
 'total_ghg_excluding_lucf',
 'trade_co2',
 'trade_co2_share']

In [35]:
for col in co2_data.columns:
    if "co2" in col.lower():
        print(col)

cement_co2
cement_co2_per_capita
co2
co2_growth_abs
co2_growth_prct
co2_including_luc
co2_including_luc_growth_abs
co2_including_luc_growth_prct
co2_including_luc_per_capita
co2_including_luc_per_gdp
co2_including_luc_per_unit_energy
co2_per_capita
co2_per_gdp
co2_per_unit_energy
coal_co2
coal_co2_per_capita
consumption_co2
consumption_co2_per_capita
consumption_co2_per_gdp
cumulative_cement_co2
cumulative_co2
cumulative_co2_including_luc
cumulative_coal_co2
cumulative_flaring_co2
cumulative_gas_co2
cumulative_luc_co2
cumulative_oil_co2
cumulative_other_co2
flaring_co2
flaring_co2_per_capita
gas_co2
gas_co2_per_capita
land_use_change_co2
land_use_change_co2_per_capita
oil_co2
oil_co2_per_capita
other_co2_per_capita
other_industry_co2
share_global_cement_co2
share_global_co2
share_global_co2_including_luc
share_global_coal_co2
share_global_cumulative_cement_co2
share_global_cumulative_co2
share_global_cumulative_co2_including_luc
share_global_cumulative_coal_co2
share_global_cumulative_flaring_co2
share_global_cumulative_gas_co2
share_global_cumulative_luc_co2
share_global_cumulative_oil_co2
share_global_cumulative_other_co2
share_global_flaring_co2
share_global_gas_co2
share_global_luc_co2
share_global_oil_co2
share_global_other_co2
temperature_change_from_co2
trade_co2
trade_co2_share

In [36]:
co2_data.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1750,AFG,2802560.0,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1751,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1752,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1753,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1754,AFG,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
energy_data = data[
    [
        'country',
        'year',
        'renewables_share_energy'
    ]
]

In [39]:
co2_clean = co2_data[
    [
        'country',
        'year',
        'co2'
    ]
]

In [40]:
merged_data = pd.merge(
    energy_data,
    co2_clean,
    on=['country', 'year'],
    how='inner'
)

In [41]:
merged_data.shape

(18063, 4)

In [42]:
merged_data.head()

       country  year  renewables_share_energy  co2
0  Afghanistan  1900                      NaN  NaN
1  Afghanistan  1901                      NaN  NaN
2  Afghanistan  1902                      NaN  NaN
3  Afghanistan  1903                      NaN  NaN
4  Afghanistan  1904                      NaN  NaN

In [43]:
countries = [
    "Germany",
    "India",
    "China",
    "United States",
    "France",
    "Spain",
    "Italy"
]

project_data = merged_data[
    merged_data['country'].isin(countries)
]

In [44]:
project_data = project_data[
    (project_data['year'] >= 2000)
    &
    (project_data['year'] <= 2023)
]

In [45]:
project_data = project_data.dropna()

In [46]:
project_data.shape

(168, 4)

In [47]:
project_data.head()

     country  year  renewables_share_energy       co2
3632   China  2000                 5.335688  3643.810
3633   China  2001                 6.251407  3724.114
3634   China  2002                 5.921867  4098.181
3635   China  2003                 5.001339  4835.251
3636   China  2004                 5.289435  5210.961

In [48]:
project_data.to_csv(
    "../data/processed/final_project_data.csv",
    index=False
)